[platformio]
src_dir = main

[env:esp32-s3-devkitc-1]
platform = espressif32@^6.8.0
framework = espidf
board = esp32-s3-devkitc-1
board_build.partitions = partitions_example.csv
monitor_filters = direct
monitor_speed = 115200
